# Generated by Django 5.1.6 on 2025-03-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('subrace', models.CharField(blank=True, max_length=50, null=True)),
                ('character_class', models.CharField(max_length=50)),
                ('subclass', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(default=1)),
                ('background', models.CharField(max_length=50)),
                ('alignment', models.CharField(max_length=50)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('skill_proficiencies', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('background_story', models.TextField(blank=True, null=True)),
                ('personality', models.TextField(blank=True, null=True)),
                ('ideal', models.TextField(blank=True, null=True)),
                ('bond', models.TextField(blank=True, null=True)),
                ('flaw', models.TextField(blank=True, null=True)),
                ('portrait_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
